### ISSUE TITLE
Deleting API Doesn't Return APIs 

### ISSUE THREAD

**Issue by forrestmid** [zfcampus/zf-apigility-admin#222]
When deleting an API, the API gets deleted, and the page then goes to a blank APIs page  without the other APIs. It clears the API list but fails to fetch the new API list. The following error is returned from GET after a successful DELETE.

``` php
Fatal error:  Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (test) could not be initialized.' in /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:189
Stack trace:
#0 /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(163): Zend\ModuleManager\ModuleManager-&gt;loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(90): Zend\ModuleManager\ModuleManager-&gt;loadModule('test')
#2 [internal function]: Zend\ModuleManager\ModuleManager-&gt;onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
#4 /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframewo in /media/psf/Home/phpstormprojects/api/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 189
```

**Comment by michalbundyra** [comment]
This repository has been closed and moved to laminas-api-tools/api-tools-admin; a new issue has been opened at https://github.com/laminas-api-tools/api-tools-admin/issues/46.
