### ISSUE TITLE
Authorization not working after Update and API completly public

### ISSUE THREAD

**Issue by andreasKrauseWebular** [zfcampus/zf-apigility-admin#394]
Hello,
today we found a fatal issue and tried to figure out what happend. Our API was fully unauthorized availible.
We found out that: (our last commit was on 2018-04-17) the config generated with the Apigility admin looked like:
`
'zf-mvc-auth' => array(
        'authorization' => array(
            'fxa\\V1\\Rpc\\Apitest\\Controller' => array(
                'actions' => array(
                    'apitest' => array(
                        'GET' => false,
                        'POST' => true,
                        'PUT' => false,
                        'PATCH' => false,
                        'DELETE' => false,
                    ),
                ),
            ),
            'fxa\\V1\\Rpc\\GetFxaReviewList\\Controller' => array(
                'actions' => array(
                    'GetFxaReviewList' => array(
`
Now we found out that the **Actions** should be written in **Uppercase** what feels a bit unexpected  that means the newer version of the apigility admin generates:
`
'zf-mvc-auth' => array(
        'authorization' => array(
            'fxa\\V1\\Rpc\\Apitest\\Controller' => array(
                'actions' => array(
                    'Apitest' => array(
                        'GET' => false,
                        'POST' => true,
`
-> that caused 

1. that for the lowercase version created before the authorization did not work and the calls where reachable publicly
2. that the checkbox for the call under authorization in the apipgility-admin was unchecked
3. and you get a fatal when you recheck it because it ll insert both lower- and uppercase ->

> Fatal error: Uncaught Zend\Permissions\Acl\Exception\InvalidArgumentException: Resource id 'fxa\V1\Rpc\GetRadiologistResult\Controller::getRadiologistResult' already exists in the ACL in /var/www/web13/html/qdicom/dev/vendor/zendframework/zend-permissions-acl/src/Acl.php:242 Stack trace: #0 /var/www/web13/html/qdicom/dev/vendor/zfcampus/zf-mvc-auth/src/Authorization/AclAuthorizationFactory.php(77): Zend\Permissions\Acl\Acl->addResource(Object(Zend\Permissions\Acl\Resource\GenericResource)) #1 /var/www/web13/html/qdicom/dev/vendor/zfcampus/zf-mvc-auth/src/Authorization/AclAuthorizationFactory.php(59): ZF\MvcAuth\Authorization\AclAuthorizationFactory::injectGrant(Object(ZF\MvcAuth\Authorization\AclAuthorization), 'deny', Array) #2 /var/www/web13/html/qdicom/dev/vendor/zfcampus/zf-mvc-auth/src/Authorization/AclAuthorizationFactory.php(38): ZF\MvcAuth\Authorization\AclAuthorizationFactory::injectGrants(Object(ZF\MvcAuth\Authorization\AclAuthorization), 'deny', Array) #3 /var/www/web13/html/qdicom/dev/vendor/zfcampus/zf-mvc-au in /var/www/web13/html/qdicom/dev/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

I corrected manually!
Can someone approve this? Or do i have an issue somewhere else? I only used the apigitlity admin for the gerneration of the config ... no manual changes until today

**Comment by weierophinney** [comment]
If I'm understanding correctly, you're defining ACLs for an RPC service. That configuration should look like:

```php
'zf-mvc-auth' => [
    'authorization' => [
        'Controller\Service\Name' => [
            'actions' => [
                'actionName' => [
                    'default' => boolean,
                    'GET' => boolean, // etc.
            ],
        ],
    ],
],
```

What you've observed was that you previously specified an action name in the configuration as `apitest`, but after an update recently, it was changed to `Apitest`, which is causing it to break.

Is this a correct summation?

If so, a cursory glance through our code doesn't show any place where we are modifying the action keys. I'll keep digging to see if I can find something.

Can you tell me what versions of each of the following modules are present, please?

- zfcampus/zf-apigility-admin
- zfcampus/zf-apigility-admin-ui
- zfcampus/zf-mvc-auth

(You can get these by running `composer show` in your project root.)

Even better, can you tell me what versions were _previously_ installed as well?

**Comment by andreasKrauseWebular** [comment]
These Versions

> zf-commons/zfc-base                            v0.1.2             A set of genetic (abstract) classes which are ...
zf-commons/zfc-user                            1.4.4              A generic user registration and authentication...
zf-commons/zfc-user-doctrine-orm               1.0.2              Doctrine2 ORM storage adapter for ZfcUser.
zfcampus/zf-api-problem                        1.3.0              ZF2 Module providing API-Problem assets and re...
zfcampus/zf-apigility                          1.4.0              Apigility module for Zend Framework
zfcampus/zf-apigility-admin                    1.5.13             Apigility Admin module
zfcampus/zf-apigility-admin-ui                 1.3.9              Apigility Admin UI module
zfcampus/zf-apigility-doctrine                 2.2.0              Apigility Doctrine module
zfcampus/zf-apigility-provider                 1.3.0              Apigility interfaces
zfcampus/zf-asset-manager                      1.2.0              Composer plugin for copying module assets into...
zfcampus/zf-configuration                      1.3.3              Zend Framework module providing a REST resourc...
zfcampus/zf-content-negotiation                1.4.0              ZF Module providing content-negotiation features
zfcampus/zf-content-validation                 1.6.0              Zend Framework module providing incoming conte...
zfcampus/zf-development-mode                   2.1.2              ZF2 development mode module
zfcampus/zf-hal                                1.5.0              ZF2 Module providing Hypermedia Application La...
zfcampus/zf-mvc-auth                           1.5.1              ZF2 Module providing Authentication and Author...
zfcampus/zf-oauth2                             1.4.0              ZF2 module for implementing an OAuth2 server
zfcampus/zf-rest                               1.5.0              ZF Module providing structure for RESTful reso...
zfcampus/zf-rpc                                1.4.0              ZF2 Module for simplifying the creation of RPC...
zfcampus/zf-versioning                         1.3.0              ZF2 Module providing listeners and route proto...

create that:

![image](https://user-images.githubusercontent.com/1299039/45308853-b8475c00-b522-11e8-9040-5c0b823e61f8.png)

using:
![image](https://user-images.githubusercontent.com/1299039/45308922-dc0aa200-b522-11e8-82d8-f66da613dca5.png)

**Comment by andreasKrauseWebular** [comment]
Controller looks like: 
`<?php
namespace fxa\V1\Rpc\Apitest;

use Zend\Mvc\Controller\AbstractActionController;
use ZF\ContentNegotiation\ViewModel;
use Application\Constant;
use Zend\ServiceManager\ServiceLocatorInterface;

class ApitestController extends AbstractActionController
{
    /**
     * @var ServiceLocatorInterface
     */
    protected $serviceLocator;

    /**
     * @return ServiceLocatorInterface
     */
    public function getServiceLocator()
    {
        return $this->serviceLocator;
    }

    /**
     * @param ServiceLocatorInterface $serviceLocator
     * @return MessageController
     */
    public function setServiceLocator(ServiceLocatorInterface $serviceLocator)
    {
        $this->serviceLocator = $serviceLocator;
        return $this;
    }

    public function apitestAction()
    {
        /** @var \Application\Service\ApplicationService $appService */
        $appService = $this->serviceLocator->get(Constant::APPLICATION_SERVICE);
        $result = $appService->findDicomByStudy($this->params()->fromPost()["study"]);

        return new ViewModel(array(
            'dicomByStudy' => $result,
        ));
    }
}`

**Comment by weierophinney** [comment]
You will need to update to the latest zf-apigility-admin-ui:

```bash
$ composer update zfcampus/zf-apigility-admin-ui
```

**Comment by andreasKrauseWebular** [comment]
The risk and mean thing if this bug is: if you have an old configuration in lowercase, your API is suddenly publicly available because the Actionnames do not fit and it looks like nothing is configured. We found out by accident that our API was fully open.

**Comment by andreasKrauseWebular** [comment]
Thank you for the quick fix!

**Comment by andreasKrauseWebular** [comment]
It s still not working completely:
It creates the right code in the module,config:
```php
'zf-mvc-auth' => array(
        'authorization' => array(
            'fxa\\V1\\Rpc\\Apitest\\Controller' => array(
                'actions' => array(
                    'apitest' => array(
                        'GET' => false,
                        'POST' => true,
                        'PUT' => false,
                        'PATCH' => false,
                        'DELETE' => false,
                    ),
                ),
            ),
```

but the UI can not read it:
![image](https://user-images.githubusercontent.com/1299039/45323902-d9bd3d80-b54c-11e8-90fc-2d46099768d9.png)

The Authorization now works fine again

**Comment by andreasKrauseWebular** [comment]
Everything works now! Thanks

**Comment by andreasKrauseWebular** [comment]
All is working now.
Thank you.
